version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '2020:80'
        volumes:
            - ./app:/var/www/html

    db:
        image: postgres
        restart: always
        ports:
          - '1010:5432'
        environment:
          POSTGRES_DB: blog
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
        volumes:
            - ./database/blog.sql:/docker-entrypoint-initdb.d/blog.sql

    adminer:
      image: adminer
      restart: always
      ports:
        - '8080:8080'