index:
    path: /
    controller: App\Controller\PostController
    action: home

showOne:
    path: /post/{id}/{truc}/{machin}
    controller: App\Controller\PostController
    action: showOne
    methods:
        - GET
        - POST

login:
    path: /login
    controller: App\Controller\SecurityController
    action: login
